development:
  postgresql:
    adapter: postgresql
    encoding: unicode
    username: <%= ENV['POSTGRESQL_USERNAME'] %>
    password: <%= ENV['POSTGRESQL_PASSWORD'] %>
    host: <%= ENV['POSTGRESQL_HOST'] %>
    port: <%= ENV['POSTGRESQL_PORT'] %>

  mssql:
    adapter: sqlserver
    username: <%= ENV['MSSQL_USERNAME'] %>
    password: <%= ENV['MSSQL_PASSWORD'] %>
    host: <%= ENV['MSSQL_HOST'] %>
    port: <%= ENV['MSSQL_PORT'] %>
    encrypt: true
    trust_server_certificate: true